version: "3.9"
services:
  jupyter:
    image: nithishr/couchbase-jupyter-lab:4.1.9
    ports:
      - "8888:8888"
    environment:
      - JUPYTER_ENABLE_LAB=yes
    volumes:
      - .:/home/jovyan/work
    depends_on:
      - couchbase
  couchbase:
    image: couchbase:enterprise
    ports:
      - 8091:8091
      - 8092:8092
      - 8093:8093
      - 8094:8094
      - 11210:11210
    volumes:
      - ./couchbase_data:/opt/couchbase/var